# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lucas Bassetti
avatar: https://avatars3.githubusercontent.com/u/1014326?v=3&s=460
email: lucasbr.dafonseca@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front-End Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lucasbassetti.com.br" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: lucasbr.dafonseca
  flickr:
  github: lucasbassetti
  instagram:
  linkedin: lucas-bassetti-67909836
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
